# Docker compose file to run hello demo app
version: '3'

networks:
  default:
    external:
      name: beluga

services:
  hello:
    build:
      context: ./
      args:
        HELLO_PORT: ${HELLO_PORT:-3000}
    image: caspia/hello:latest
    container_name: hello
    environment:
      - HELLO_PORT=${HELLO_PORT:-3000}
      - VIRTUAL_HOST=hello.ed,hello.ed.local
      - VIRTUAL_PORT=${HELLO_PORT:-3000}
    ports:
     - "${HELLO_PORT:-3000}:${HELLO_PORT:-3000}"
    restart: always
    networks:
      default:
        aliases:
          - hello
